#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/kuenzel/Dokumente/Python/SCNv2/SCNv2_venv/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="SCNv2_venv/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/kuenzel/Dokumente/Python/SCNv2/x86_64/.libs/libnrnmech.so" "$@"
